apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: matrix
  POSTGRES_USER: matrix
  POSTGRES_PASSWORD: matrix
  matrix.sql: |
    CREATE USER matrix
      LOGIN
      ENCRYPTED PASSWORD matrix

    CREATE DATABASE matrix
    ENCODING 'UTF8'
    LC_COLLATE='C'
    LC_CTYPE='C'
    template=template0
    OWNER matrix